version: '3'

services:
  redis:
    image: redis:latest
    container_name: redis-local
    ports:
      - "6379:6379"

  mapper:
    build: ./mapper
    depends_on:
      - redis
    volumes:
      - .:/app
    deploy:
      replicas: 8

  reducer:
    build: ./reducer
    depends_on:
      - redis
    volumes:
      - .:/app
    deploy:
      replicas: 4
  
  coordinator:
    build: ./coordinator
    depends_on:
      - redis
      - reducer
      - mapper
    volumes:
      - .:/app
    environment:
      - NUM_MAPPERS=8
      - NUM_REDUCERS=4